apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: gcr.io/PROJECT_ID/client:latest
        ports:
        - containerPort: 3000
        env:
        - name: SERVER_URL
          value: 'http://server-service.default.svc.cluster.local:9000'
